language: node_js

node_js:
  - 7

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
  - npm install -g swagger
  
env:
  - databaseuri=localhost
  - databasecollection=test_db
