swagger: "2.0"
info:
  version: "0.0.1"
  title: MusicConnectionMachine API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json


securityDefinitions:
  DefaultSecurity:
    type: apiKey
    in: header
    name: API-KEY

paths:
  $ref: ./paths/paths.yaml

# complex objects have schema definitions
definitions:
  $ref: ./definitions/definitions.yaml
